#!/usr/bin/env python
# -*- coding: utf-8 -*-
#
# (c) Copyright 2025 Sensirion AG, Switzerland
#
#     THIS FILE IS AUTOMATICALLY GENERATED!
#
# Generator:     sensirion-driver-generator 1.3.3
# Product:       sps30
# Model-Version: 1.0.1
#

import pytest
from sensirion_uart_sps30.device import Sps30Device

from sensirion_uart_sps30.commands import (OutputFormat)


@pytest.fixture
def sensor(channel_provider):
    # Create Channel
    with channel_provider:
        channel = channel_provider.get_channel(0.05)
        dev = Sps30Device(channel)
        yield dev


def test_start_measurement1(sensor):
    sensor.start_measurement(OutputFormat(261))
    (mc_1p0, mc_2p5, mc_4p0, mc_10p0, nc_0p5, nc_1p0, nc_2p5, nc_4p0, nc_10p0, typical_particle_size
     ) = sensor.read_measurement_values_float()
    print(f"mc_1p0: {mc_1p0}; "
          f"mc_2p5: {mc_2p5}; "
          f"mc_4p0: {mc_4p0}; "
          f"mc_10p0: {mc_10p0}; "
          f"nc_0p5: {nc_0p5}; "
          f"nc_1p0: {nc_1p0}; "
          f"nc_2p5: {nc_2p5}; "
          f"nc_4p0: {nc_4p0}; "
          f"nc_10p0: {nc_10p0}; "
          f"typical_particle_size: {typical_particle_size}; "
          )
    (mc_1p0, mc_2p5, mc_4p0, mc_10p0, nc_0p5, nc_1p0, nc_2p5, nc_4p0, nc_10p0, typical_particle_size
     ) = sensor.read_measurement_values_uint16()
    print(f"mc_1p0: {mc_1p0}; "
          f"mc_2p5: {mc_2p5}; "
          f"mc_4p0: {mc_4p0}; "
          f"mc_10p0: {mc_10p0}; "
          f"nc_0p5: {nc_0p5}; "
          f"nc_1p0: {nc_1p0}; "
          f"nc_2p5: {nc_2p5}; "
          f"nc_4p0: {nc_4p0}; "
          f"nc_10p0: {nc_10p0}; "
          f"typical_particle_size: {typical_particle_size}; "
          )
    sensor.start_fan_cleaning()
    auto_cleaning_interval = sensor.read_auto_cleaning_interval()
    print(f"auto_cleaning_interval: {auto_cleaning_interval}; "
          )
    sensor.write_auto_cleaning_interval(604800)
    product_type = sensor.read_product_type()
    print(f"product_type: {product_type}; "
          )
    serial_number = sensor.read_serial_number()
    print(f"serial_number: {serial_number}; "
          )
    (firmware_major_version, firmware_minor_version, reserved1, hardware_revision, reserved2, shdlc_major_version,
     shdlc_minor_version
     ) = sensor.read_version()
    print(f"firmware_major_version: {firmware_major_version}; "
          f"firmware_minor_version: {firmware_minor_version}; "
          f"reserved1: {reserved1}; "
          f"hardware_revision: {hardware_revision}; "
          f"reserved2: {reserved2}; "
          f"shdlc_major_version: {shdlc_major_version}; "
          f"shdlc_minor_version: {shdlc_minor_version}; "
          )
    (device_status_register, reserved
     ) = sensor.read_device_status_register(1)
    print(f"device_status_register: {device_status_register}; "
          f"reserved: {reserved}; "
          )
    sensor.stop_measurement()


def test_sleep1(sensor):
    sensor.sleep()
    sensor.wake_up_sequence()


def test_read_auto_cleaning_interval1(sensor):
    auto_cleaning_interval = sensor.read_auto_cleaning_interval()
    print(f"auto_cleaning_interval: {auto_cleaning_interval}; "
          )


def test_write_auto_cleaning_interval1(sensor):
    sensor.write_auto_cleaning_interval(604800)


def test_read_product_type1(sensor):
    product_type = sensor.read_product_type()
    print(f"product_type: {product_type}; "
          )


def test_read_serial_number1(sensor):
    serial_number = sensor.read_serial_number()
    print(f"serial_number: {serial_number}; "
          )


def test_read_version1(sensor):
    (firmware_major_version, firmware_minor_version, reserved1, hardware_revision, reserved2, shdlc_major_version,
     shdlc_minor_version
     ) = sensor.read_version()
    print(f"firmware_major_version: {firmware_major_version}; "
          f"firmware_minor_version: {firmware_minor_version}; "
          f"reserved1: {reserved1}; "
          f"hardware_revision: {hardware_revision}; "
          f"reserved2: {reserved2}; "
          f"shdlc_major_version: {shdlc_major_version}; "
          f"shdlc_minor_version: {shdlc_minor_version}; "
          )


def test_read_device_status_register1(sensor):
    (device_status_register, reserved
     ) = sensor.read_device_status_register(1)
    print(f"device_status_register: {device_status_register}; "
          f"reserved: {reserved}; "
          )


def test_device_reset1(sensor):
    sensor.device_reset()

